namespace POS.Domain.Enums;

/// <summary>
/// Semantic classification of an inventory ledger movement.
/// Supersedes the legacy free-text <c>Type</c> string ("in", "out", "adjustment")
/// on <c>InventoryMovement</c>.
/// </summary>
public enum InventoryTransactionType
{
    /// <summary>
    /// Stock received from a supplier — adds to current stock.
    /// Maps to legacy <c>Type = "in"</c>.
    /// </summary>
    Purchase = 0,

    /// <summary>
    /// Automatic deduction generated by the Sync Engine when a sale is processed.
    /// Maps to legacy <c>Type = "out"</c>.
    /// </summary>
    ConsumeFromSale = 1,

    /// <summary>
    /// Controlled write-off for expired, damaged, or spilled stock.
    /// <c>Reason</c> is required for this type.
    /// Maps to legacy <c>Type = "out"</c>.
    /// </summary>
    Waste = 2,

    /// <summary>
    /// Manual delta correction after a physical inventory count.
    /// <c>Reason</c> is required. Delta may be positive (adds) or negative (subtracts).
    /// Maps to legacy <c>Type = "in"</c> or <c>"out"</c> depending on sign.
    /// </summary>
    ManualAdjustment = 3,

    /// <summary>
    /// One-time initial stock count when an ingredient is first set up.
    /// Maps to legacy <c>Type = "in"</c>.
    /// </summary>
    InitialCount = 4
}
