using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using POS.API.Filters;
using POS.Domain.Enums;
using POS.Domain.Models;
using POS.Services.IService;

namespace POS.API.Controllers;

/// <summary>
/// Manages print jobs generated by the Sync Engine for kitchen, bar, and waiter stations.
/// Peripheral devices (printers, KDS tablets) poll this controller for pending jobs
/// and acknowledge completion or failure.
/// </summary>
[Route("api/print-jobs")]
[RequiresFeature(FeatureKey.KdsBasic)]
public class PrintJobController : BaseApiController
{
    private readonly IPrintJobService _printJobService;

    public PrintJobController(IPrintJobService printJobService)
    {
        _printJobService = printJobService;
    }

    /// <summary>
    /// Returns all active print jobs for the current branch.
    /// Includes both <see cref="PrintJobStatus.Pending"/> and <see cref="PrintJobStatus.InProgress"/> jobs,
    /// ordered FIFO by <c>CreatedAt</c>.
    /// Used by printers and KDS tablets to poll for new and in-progress work.
    /// </summary>
    /// <param name="destination">
    /// Optional filter: <c>0</c> = Kitchen, <c>1</c> = Bar, <c>2</c> = Waiters.
    /// Omit to retrieve active jobs for all destinations.
    /// </param>
    /// <returns>List of active <see cref="PrintJob"/>s.</returns>
    /// <response code="200">Returns the list of active print jobs.</response>
    [HttpGet("pending")]
    [Authorize(Roles = "Owner,Manager,Cashier,Kitchen,Waiter")]
    [ProducesResponseType(typeof(IEnumerable<PrintJob>), StatusCodes.Status200OK)]
    public async Task<IActionResult> GetPending([FromQuery] PrintingDestination? destination)
    {
        var jobs = await _printJobService.GetPendingAsync(BranchId, destination);
        return Ok(jobs);
    }

    /// <summary>
    /// Returns all print jobs associated with a specific order.
    /// Used by the POS front-end to display print status in the order detail view.
    /// </summary>
    /// <param name="orderId">The UUID of the order (36-character GUID string).</param>
    /// <returns>All <see cref="PrintJob"/>s for the given order.</returns>
    /// <response code="200">Returns the list of print jobs for the order.</response>
    [HttpGet("by-order/{orderId}")]
    [Authorize(Roles = "Owner,Manager,Cashier,Kitchen,Waiter")]
    [ProducesResponseType(typeof(IEnumerable<PrintJob>), StatusCodes.Status200OK)]
    public async Task<IActionResult> GetByOrder(string orderId)
    {
        var jobs = await _printJobService.GetByOrderAsync(orderId);
        return Ok(jobs);
    }

    /// <summary>
    /// Transitions a print job to <see cref="PrintJobStatus.InProgress"/>.
    /// Signals that a KDS operator acknowledged the ticket and is actively preparing the items.
    /// Only valid from <see cref="PrintJobStatus.Pending"/> status.
    /// </summary>
    /// <param name="id">The ID of the print job to transition.</param>
    /// <returns>No content on success.</returns>
    /// <response code="204">Transition applied successfully.</response>
    /// <response code="404">If the print job is not found or does not belong to this branch.</response>
    /// <response code="400">If the job is not in <see cref="PrintJobStatus.Pending"/> status.</response>
    [HttpPatch("{id:int}/in-progress")]
    [Authorize(Roles = "Owner,Manager,Cashier,Kitchen,Waiter")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> MarkInProgress(int id)
    {
        try
        {
            var found = await _printJobService.MarkAsInProgressAsync(id, BranchId);
            return found ? NoContent() : NotFound();
        }
        catch (POS.Domain.Exceptions.ValidationException ex)
        {
            return BadRequest(ex.Message);
        }
    }

    /// <summary>
    /// Marks a print job as <see cref="PrintJobStatus.Printed"/>.
    /// Sets <c>PrintedAt</c> to the current UTC timestamp.
    /// Valid from both <see cref="PrintJobStatus.Pending"/> and <see cref="PrintJobStatus.InProgress"/> status.
    /// Called by the peripheral device after a successful print or by the KDS when the order is ready.
    /// </summary>
    /// <param name="id">The ID of the print job to acknowledge.</param>
    /// <returns>The updated <see cref="PrintJob"/>.</returns>
    /// <response code="200">Returns the updated print job.</response>
    /// <response code="404">If the print job is not found or does not belong to this branch.</response>
    /// <response code="400">If the job is already in a terminal state (<see cref="PrintJobStatus.Printed"/> or <see cref="PrintJobStatus.Failed"/>).</response>
    [HttpPatch("{id:int}/printed")]
    [Authorize(Roles = "Owner,Manager,Cashier,Kitchen,Waiter")]
    [ProducesResponseType(typeof(PrintJob), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> MarkPrinted(int id)
    {
        try
        {
            var job = await _printJobService.MarkPrintedAsync(id, BranchId);
            return job != null ? Ok(job) : NotFound();
        }
        catch (POS.Domain.Exceptions.ValidationException ex)
        {
            return BadRequest(ex.Message);
        }
    }

    /// <summary>
    /// Records a failed print attempt for a job.
    /// Increments <c>AttemptCount</c> and transitions to <see cref="PrintJobStatus.Failed"/>
    /// when the maximum number of attempts (<c>3</c>) is reached.
    /// </summary>
    /// <param name="id">The ID of the print job that failed.</param>
    /// <returns>The updated <see cref="PrintJob"/>.</returns>
    /// <response code="200">Returns the updated print job.</response>
    /// <response code="404">If the print job is not found or does not belong to this branch.</response>
    /// <response code="400">If the job is not in <see cref="PrintJobStatus.Pending"/> status.</response>
    [HttpPatch("{id:int}/failed")]
    [Authorize(Roles = "Owner,Manager,Cashier,Kitchen,Waiter")]
    [ProducesResponseType(typeof(PrintJob), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> MarkFailed(int id)
    {
        try
        {
            var job = await _printJobService.MarkFailedAsync(id, BranchId);
            return job != null ? Ok(job) : NotFound();
        }
        catch (POS.Domain.Exceptions.ValidationException ex)
        {
            return BadRequest(ex.Message);
        }
    }
}
