using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using POS.Domain.Enums;
using POS.Domain.Models;
using POS.Repository;

namespace POS.API.Controllers;

/// <summary>
/// Manages print jobs generated by the Sync Engine for kitchen, bar, and waiter stations.
/// Peripheral devices (printers, KDS tablets) poll this controller for pending jobs
/// and acknowledge completion or failure.
/// </summary>
[Route("api/print-jobs")]
public class PrintJobController : BaseApiController
{
    private const int MaxAttempts = 3;

    private readonly IUnitOfWork _unitOfWork;

    public PrintJobController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    /// <summary>
    /// Returns all pending print jobs for the current branch.
    /// Results are ordered FIFO by <c>CreatedAt</c>.
    /// Used by printers and KDS tablets to poll for new work.
    /// </summary>
    /// <param name="destination">
    /// Optional filter: <c>0</c> = Kitchen, <c>1</c> = Bar, <c>2</c> = Waiters.
    /// Omit to retrieve pending jobs for all destinations.
    /// </param>
    /// <returns>List of pending <see cref="PrintJob"/>s.</returns>
    /// <response code="200">Returns the list of pending print jobs.</response>
    [HttpGet("pending")]
    [Authorize(Roles = "Owner,Manager,Cashier,Kitchen,Waiter")]
    [ProducesResponseType(typeof(IEnumerable<PrintJob>), StatusCodes.Status200OK)]
    public async Task<IActionResult> GetPending([FromQuery] PrintingDestination? destination)
    {
        var jobs = await _unitOfWork.PrintJobs.GetPendingByBranchAsync(BranchId, destination);
        return Ok(jobs);
    }

    /// <summary>
    /// Returns all print jobs associated with a specific order.
    /// Used by the POS front-end to display print status in the order detail view.
    /// </summary>
    /// <param name="orderId">The UUID of the order (36-character GUID string).</param>
    /// <returns>All <see cref="PrintJob"/>s for the given order.</returns>
    /// <response code="200">Returns the list of print jobs for the order.</response>
    [HttpGet("by-order/{orderId}")]
    [Authorize(Roles = "Owner,Manager,Cashier,Kitchen,Waiter")]
    [ProducesResponseType(typeof(IEnumerable<PrintJob>), StatusCodes.Status200OK)]
    public async Task<IActionResult> GetByOrder(string orderId)
    {
        var jobs = await _unitOfWork.PrintJobs.GetByOrderAsync(orderId);
        return Ok(jobs);
    }

    /// <summary>
    /// Marks a print job as <see cref="PrintJobStatus.Printed"/>.
    /// Sets <c>PrintedAt</c> to the current UTC timestamp.
    /// Called by the peripheral device after a successful print.
    /// </summary>
    /// <param name="id">The ID of the print job to acknowledge.</param>
    /// <returns>The updated <see cref="PrintJob"/>.</returns>
    /// <response code="200">Returns the updated print job.</response>
    /// <response code="404">If the print job is not found or does not belong to this branch.</response>
    /// <response code="400">If the job is not in <see cref="PrintJobStatus.Pending"/> state.</response>
    [HttpPatch("{id:int}/printed")]
    [Authorize(Roles = "Owner,Manager,Cashier,Kitchen,Waiter")]
    [ProducesResponseType(typeof(PrintJob), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> MarkPrinted(int id)
    {
        var job = await _unitOfWork.PrintJobs.GetByIdAsync(id);
        if (job == null || job.BranchId != BranchId) return NotFound();

        if (job.Status != PrintJobStatus.Pending)
            return BadRequest($"Print job {id} is already in status '{job.Status}'.");

        job.Status    = PrintJobStatus.Printed;
        job.PrintedAt = DateTime.UtcNow;
        _unitOfWork.PrintJobs.Update(job);
        await _unitOfWork.SaveChangesAsync();

        return Ok(job);
    }

    /// <summary>
    /// Records a failed print attempt for a job.
    /// Increments <c>AttemptCount</c> and transitions to <see cref="PrintJobStatus.Failed"/>
    /// when the maximum number of attempts (<c>3</c>) is reached.
    /// </summary>
    /// <param name="id">The ID of the print job that failed.</param>
    /// <returns>The updated <see cref="PrintJob"/>.</returns>
    /// <response code="200">Returns the updated print job.</response>
    /// <response code="404">If the print job is not found or does not belong to this branch.</response>
    /// <response code="400">If the job is not in <see cref="PrintJobStatus.Pending"/> state.</response>
    [HttpPatch("{id:int}/failed")]
    [Authorize(Roles = "Owner,Manager,Cashier,Kitchen,Waiter")]
    [ProducesResponseType(typeof(PrintJob), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> MarkFailed(int id)
    {
        var job = await _unitOfWork.PrintJobs.GetByIdAsync(id);
        if (job == null || job.BranchId != BranchId) return NotFound();

        if (job.Status != PrintJobStatus.Pending)
            return BadRequest($"Print job {id} is already in status '{job.Status}'.");

        job.AttemptCount++;

        if (job.AttemptCount >= MaxAttempts)
            job.Status = PrintJobStatus.Failed;

        _unitOfWork.PrintJobs.Update(job);
        await _unitOfWork.SaveChangesAsync();

        return Ok(job);
    }
}
