using System.ComponentModel.DataAnnotations;

namespace POS.Domain.Models;

/// <summary>
/// Short-lived, single-use code that lets an already-activated device redeem
/// its binding to a specific <see cref="CashRegister"/> from the terminal UI.
/// Generated by an admin in the back office; redeemed by the device itself
/// authenticated with its long-lived device JWT (Mode B).
///
/// Distinct from <see cref="DeviceActivationCode"/>, which bootstraps a fresh
/// terminal. This code is for binding a terminal that is already paired but
/// not yet linked to a register.
/// </summary>
public class CashRegisterLinkCode
{
    public int Id { get; set; }

    [Required]
    [MaxLength(6)]
    public string Code { get; set; } = null!;

    public int CashRegisterId { get; set; }

    public DateTime ExpiresAt { get; set; }

    public bool IsUsed { get; set; }

    public DateTime? UsedAt { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public virtual CashRegister CashRegister { get; set; } = null!;
}
