using System.ComponentModel.DataAnnotations;
using POS.Domain.Enums;

namespace POS.Domain.Models;

/// <summary>
/// Represents a single print job generated when an order is confirmed.
/// Each job targets one physical area (<see cref="PrintingDestination"/>)
/// and contains only the items routed to that area.
/// Lifecycle: Pending → Printed (acknowledged by peripheral) | Failed (max attempts exceeded).
/// </summary>
public partial class PrintJob
{
    /// <summary>Primary key — auto-generated by the database.</summary>
    public int Id { get; set; }

    /// <summary>
    /// Foreign key to the <see cref="Order"/> that originated this job.
    /// Matches the client UUID format (GUID string, 36 chars).
    /// </summary>
    [Required]
    [MaxLength(36)]
    public string OrderId { get; set; } = null!;

    /// <summary>
    /// Branch this print job belongs to.
    /// Used to scope polling queries per printer/KDS without requiring a token claim.
    /// </summary>
    public int BranchId { get; set; }

    /// <summary>
    /// Physical area where the ticket must be sent.
    /// Stored as <c>int</c> in the database; serialized as a string in the API.
    /// </summary>
    public PrintingDestination Destination { get; set; }

    /// <summary>
    /// Current lifecycle state of this print job.
    /// Default is <see cref="PrintJobStatus.Pending"/> on creation.
    /// </summary>
    public PrintJobStatus Status { get; set; } = PrintJobStatus.Pending;

    /// <summary>
    /// Pre-rendered plain-text ticket content in ESC/POS-ready format.
    /// The server does not interpret the format; it stores the string as-is
    /// for the client peripheral to dispatch directly to the printer.
    /// Using <c>nvarchar(max)</c> to accommodate any future richer formats (JSON, ZPL, etc.)
    /// without schema changes.
    /// </summary>
    [Required]
    public string RawContent { get; set; } = null!;

    /// <summary>UTC timestamp when the print job was created by the Sync Engine.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// UTC timestamp set by the peripheral when it confirms a successful print.
    /// Null while the job is in <see cref="PrintJobStatus.Pending"/> or <see cref="PrintJobStatus.Failed"/> state.
    /// </summary>
    public DateTime? PrintedAt { get; set; }

    /// <summary>
    /// Number of times the peripheral attempted (and failed) to print this job.
    /// When <c>AttemptCount</c> reaches 3 the status is automatically set to <see cref="PrintJobStatus.Failed"/>.
    /// </summary>
    public int AttemptCount { get; set; } = 0;

    // ── Navigation properties ──

    /// <summary>Navigation to the parent order.</summary>
    public virtual Order? Order { get; set; }

    /// <summary>Navigation to the branch.</summary>
    public virtual Branch? Branch { get; set; }
}
