namespace POS.Domain.Models;

/// <summary>
/// Summary metrics for a date range report.
/// </summary>
public class ReportSummary
{
    public DateTime From { get; set; }
    public DateTime To { get; set; }
    public int TotalOrders { get; set; }
    public int CancelledOrders { get; set; }
    public int CompletedOrders { get; set; }
    public int TotalCents { get; set; }
    public int CashCents { get; set; }
    public int CardCents { get; set; }
    public int TotalDiscountCents { get; set; }
    public decimal AverageTicketCents { get; set; }
    public List<DailySummary> DailySummaries { get; set; } = new();
    public List<TopProduct> TopProducts { get; set; } = new();
    public List<OrderReportRow> Orders { get; set; } = new();
}

/// <summary>
/// Sales summary for a single day.
/// </summary>
public class DailySummary
{
    public DateTime Date { get; set; }
    public int OrderCount { get; set; }
    public int TotalCents { get; set; }
    public int CancelledCount { get; set; }
}

/// <summary>
/// Top selling product in the report period.
/// </summary>
public class TopProduct
{
    public string Name { get; set; } = string.Empty;
    public int Quantity { get; set; }
    public int TotalCents { get; set; }
}

/// <summary>
/// Single order row for the report table.
/// </summary>
public class OrderReportRow
{
    public int OrderNumber { get; set; }
    public DateTime CreatedAt { get; set; }
    public int TotalCents { get; set; }
    public int TotalDiscountCents { get; set; }
    public string PaymentMethod { get; set; } = string.Empty;
    public string Status { get; set; } = string.Empty;
    public string? CancellationReason { get; set; }
    public int ItemCount { get; set; }
}

// ──────────────────────────────────────────
// BDD-006: Advanced BI & Reporting — DTOs
// ──────────────────────────────────────────

/// <summary>
/// A single data point in a time-series sales chart.
/// </summary>
public class SalesPointDto
{
    /// <summary>Bucket start date/time (truncated to the requested granularity).</summary>
    public DateTime Date { get; set; }

    /// <summary>Total revenue for this bucket, in cents.</summary>
    public int TotalCents { get; set; }

    /// <summary>Number of paid, non-cancelled orders in this bucket.</summary>
    public int OrderCount { get; set; }
}

/// <summary>
/// Top-selling product aggregated over the report period.
/// </summary>
public class TopProductDto
{
    /// <summary>Product name as recorded on the order item.</summary>
    public string ProductName { get; set; } = string.Empty;

    /// <summary>Total units sold across all matching orders.</summary>
    public int QuantitySold { get; set; }

    /// <summary>Total revenue generated by this product, in cents.</summary>
    public int TotalRevenueCents { get; set; }
}

/// <summary>
/// Sales breakdown by payment method and optional provider.
/// </summary>
public class PaymentMethodSalesDto
{
    /// <summary>Payment method name (e.g., "Cash", "Card").</summary>
    public string PaymentMethod { get; set; } = string.Empty;

    /// <summary>External payment provider (e.g., "Clip", "MercadoPago"), or null for manual payments.</summary>
    public string? Provider { get; set; }

    /// <summary>Total amount collected through this method/provider combination, in cents.</summary>
    public int TotalCents { get; set; }

    /// <summary>Number of individual payment transactions.</summary>
    public int TransactionCount { get; set; }
}

/// <summary>
/// Aggregated chart data for the BI dashboard.
/// </summary>
public class DashboardChartsDto
{
    /// <summary>Time-series revenue and order count, bucketed by the requested granularity.</summary>
    public List<SalesPointDto> SalesOverTime { get; set; } = new();

    /// <summary>Top 10 products by quantity sold, descending.</summary>
    public List<TopProductDto> TopProducts { get; set; } = new();

    /// <summary>Revenue and transaction count broken down by payment method and provider.</summary>
    public List<PaymentMethodSalesDto> SalesByPaymentMethod { get; set; } = new();
}
